"""fix schemes

Revision ID: 3bd2eb8cf5b2
Revises: adc365b3c119
Create Date: 2025-04-18 20:06:14.102500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bd2eb8cf5b2'
down_revision: Union[str, None] = 'adc365b3c119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_constraint('assets_asset_project_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['asset_project_id'], ['project_id'], ondelete='CASCADE')

    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.drop_constraint('chunks_chunk_asset_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('chunks_chunk_project_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['chunk_project_id'], ['project_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'assets', ['chunk_asset_id'], ['asset_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('chunks_chunk_project_id_fkey', 'projects', ['chunk_project_id'], ['project_id'])
        batch_op.create_foreign_key('chunks_chunk_asset_id_fkey', 'assets', ['chunk_asset_id'], ['asset_id'])

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('assets_asset_project_id_fkey', 'projects', ['asset_project_id'], ['project_id'])

    # ### end Alembic commands ###
