"""chat table edited

Revision ID: adc365b3c119
Revises: d77b5366226c
Create Date: 2025-04-18 16:35:12.072378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adc365b3c119'
down_revision: Union[str, None] = 'd77b5366226c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_uuid', sa.UUID(), nullable=False))
        batch_op.drop_constraint('chats_user_uuid_key', type_='unique')
        batch_op.create_unique_constraint(None, ['chat_uuid'])
        batch_op.drop_column('user_uuid')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_uuid', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('chats_user_uuid_key', ['user_uuid'])
        batch_op.drop_column('chat_uuid')

    # ### end Alembic commands ###
