"""Add new models

Revision ID: d77b5366226c
Revises: 
Create Date: 2025-04-17 08:41:42.969698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd77b5366226c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user__uuid', sa.UUID(), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('firebase_uid'),
    sa.UniqueConstraint('user__uuid')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_user_email', ['email'], unique=False)
        batch_op.create_index('ix_user_firebase_uid', ['firebase_uid'], unique=False)

    op.create_table('chats',
    sa.Column('chat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id'),
    sa.UniqueConstraint('user_uuid')
    )
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.create_index('ix_chat_project_id', ['project_id'], unique=False)
        batch_op.create_index('ix_chat_user_id', ['user_id'], unique=False)

    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_uuid', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('is_user', sa.Boolean(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id'),
    sa.UniqueConstraint('message_uuid')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_message_chat_id', ['chat_id'], unique=False)

    with op.batch_alter_table('collection_1024_1', schema=None) as batch_op:
        batch_op.drop_index('collection_1024_1_vector_idx', postgresql_using='ivfflat')

    op.drop_table('collection_1024_1')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_1024_1',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name='collection_1024_1_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_1024_1_pkey')
    )
    with op.batch_alter_table('collection_1024_1', schema=None) as batch_op:
        batch_op.create_index('collection_1024_1_vector_idx', ['vector'], unique=False, postgresql_using='ivfflat')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_message_chat_id')

    op.drop_table('messages')
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_user_id')
        batch_op.drop_index('ix_chat_project_id')

    op.drop_table('chats')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_user_firebase_uid')
        batch_op.drop_index('ix_user_email')

    op.drop_table('users')
    # ### end Alembic commands ###
