from enum import Enum

class ResponseSignal(Enum):

    FILE_VALIDATED_SUCCESS = "file_validate_successfully"
    FILE_TYPE_NOT_SUPPORTED = "file_type_not_supported"
    FILE_SIZE_EXCEEDED = "file_size_exceeded"
    FILE_UPLOAD_SUCCESS = "file_upload_success"
    FILE_UPLOAD_FAILED = "file_upload_failed"
    PROCESSING_SUCCESS = "processing_success"
    PROCESSING_FAILED = "processing_failed"
    NO_FILES_ERROR = "not_found_files"
    FILE_ID_ERROR = "no_file_found_with_this_id"
    PROJECT_NOT_FOUND_ERROR = "project_not_found"
    INSERT_INTO_VECTORDB_ERROR = "insert_into_vectordb_error"
    INSERT_INTO_VECTORDB_SUCCESS = "insert_into_vectordb_success"
    VECTORDB_COLLECTION_RETRIEVED = "vectordb_collection_retrieved"
    VECTORDB_SEARCH_ERROR = "vectordb_search_error"
    VECTORDB_SEARCH_SUCCESS = "vectordb_search_success"
    RAG_ANSWER_ERROR = "rag_answer_error"
    RAG_ANSWER_SUCCESS = "rag_answer_success"
    CHAT_CREATED_SUCCESS = "chat_created_success"
    CHATS_FETCHED_SUCCESS= "chats_fetched_success"
    CHAT_NOT_FOUND= "chat_not_found"
    CHAT_FETCHED_SUCCESS= "chat_fetched_success"
    BAD_REQUEST= "bad_request"
    CHAT_DELETED_SUCCESS= "chat_deleted_success"
    MESSAGE_CREATED_SUCCESS= "message_created_success"
    MESSAGES_FETCHED_SUCCESS= "messages_fetched_success"
    MESSAGE_NOT_FOUND= "message_not_found"
    MESSAGE_FETCHED_SUCCESS= "message_fetched_success"
    MESSAGE_DELETED_SUCCESS= "message_deleted_success"
    USERS_FETCHED_SUCCESS= "users_fetched_success"
    USER_NOT_FOUND= "user_not_found"
    USER_FETCHED_SUCCESS= "user_fetched_success"
    USER_CREATED_SUCCESS= "user_created_success"
    USER_CREATION_FAILED= "user_creation_failed"
    LOGIN_SUCCESS= "login_success"
    LOGIN_FAILED= "login_failed"
    LOGOUT_SUCCESS= "logout_success"
    LOGOUT_FAILED= "logout_failed"
    TOKEN_VERIFIED= "token_verified"
    INVALID_TOKEN= "invalid_token"
    TOKEN_NOT_VERIFIED= "token_not_verified"

    